/*
Quay Frontend

This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations.

API version: v1
Contact: admin@example.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package quay_api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateRobotFederationInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateRobotFederationInner{}

// CreateRobotFederationInner struct for CreateRobotFederationInner
type CreateRobotFederationInner struct {
	// The issuer of the token
	Issuer string `json:"issuer"`
	// The subject of the token
	Subject string `json:"subject"`
}

type _CreateRobotFederationInner CreateRobotFederationInner

// NewCreateRobotFederationInner instantiates a new CreateRobotFederationInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRobotFederationInner(issuer string, subject string) *CreateRobotFederationInner {
	this := CreateRobotFederationInner{}
	this.Issuer = issuer
	this.Subject = subject
	return &this
}

// NewCreateRobotFederationInnerWithDefaults instantiates a new CreateRobotFederationInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRobotFederationInnerWithDefaults() *CreateRobotFederationInner {
	this := CreateRobotFederationInner{}
	return &this
}

// GetIssuer returns the Issuer field value
func (o *CreateRobotFederationInner) GetIssuer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Issuer
}

// GetIssuerOk returns a tuple with the Issuer field value
// and a boolean to check if the value has been set.
func (o *CreateRobotFederationInner) GetIssuerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Issuer, true
}

// SetIssuer sets field value
func (o *CreateRobotFederationInner) SetIssuer(v string) {
	o.Issuer = v
}

// GetSubject returns the Subject field value
func (o *CreateRobotFederationInner) GetSubject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value
// and a boolean to check if the value has been set.
func (o *CreateRobotFederationInner) GetSubjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subject, true
}

// SetSubject sets field value
func (o *CreateRobotFederationInner) SetSubject(v string) {
	o.Subject = v
}

func (o CreateRobotFederationInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateRobotFederationInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["issuer"] = o.Issuer
	toSerialize["subject"] = o.Subject
	return toSerialize, nil
}

func (o *CreateRobotFederationInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"issuer",
		"subject",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateRobotFederationInner := _CreateRobotFederationInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateRobotFederationInner)

	if err != nil {
		return err
	}

	*o = CreateRobotFederationInner(varCreateRobotFederationInner)

	return err
}

type NullableCreateRobotFederationInner struct {
	value *CreateRobotFederationInner
	isSet bool
}

func (v NullableCreateRobotFederationInner) Get() *CreateRobotFederationInner {
	return v.value
}

func (v *NullableCreateRobotFederationInner) Set(val *CreateRobotFederationInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRobotFederationInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRobotFederationInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRobotFederationInner(val *CreateRobotFederationInner) *NullableCreateRobotFederationInner {
	return &NullableCreateRobotFederationInner{value: val, isSet: true}
}

func (v NullableCreateRobotFederationInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRobotFederationInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
